import React, { useState, useRef } from 'react';
import { Button } from '@/components/ui/button';
import { ScrollArea } from '@/components/ui/scroll-area';
import { Input } from '@/components/ui/input';
import { Map, Plus, Copy, Trash2, Download, FolderOpen, CheckCircle2, AlertCircle, Info, Package } from 'lucide-react';
import JSZip from 'jszip';
import CampaignForm from '../components/campaign/CampaignForm';
import CampaignCard from '../components/campaign/CampaignCard';

const STORAGE_KEY = 'm2tw_campaigns';

function loadCampaigns() {
  try {
    const s = localStorage.getItem(STORAGE_KEY);
    return s ? JSON.parse(s) : [];
  } catch { return []; }
}
function saveCampaigns(c) {
  try { localStorage.setItem(STORAGE_KEY, JSON.stringify(c)); } catch {}
}

const DEFAULT_CAMPAIGN_DESCRIPTIONS = (name, title) => `¬
{${name.toUpperCase()}_WESTERN_EUROPE_TITLE}Crusade for the Holy Land
{${name.toUpperCase()}_VICTORY_SHORT}Short Campaign
{${name.toUpperCase()}_VICTORY_LONG}Long Campaign
{${name.toUpperCase()}_DESCRIPTION}A custom campaign based on ${title}.
{${name.toUpperCase()}_TITLE}${title}
`;

const DEFAULT_DESCR_STRAT = (name) => `; Custom campaign script generated by Mylae's Rome: Total War Mod Editor

campaign\t\t${name}

start_date\t1080 summer
end_date\t1530 winter
timescale\t2

script
\tcampaign_script.txt

playable
end

unlockable
end

nonplayable
end

; ── Factions ──────────────────────────────────────────────────────────────────
; Load this file in Campaign Map Editor > Strat tab and use the Factions sub-tab
; to add faction blocks with AI labels, treasury, and status flags.
; Each active faction needs: faction name, economicAI militaryAI, ai_label, denari, denari_kings_purse

; ── Regions / Settlements ─────────────────────────────────────────────────────
; Use Campaign Map Editor > Strat > Settlements tab to add settlement blocks.
; Each region defined in descr_regions.txt must have a matching settlement block here.

; ── Diplomacy ─────────────────────────────────────────────────────────────────
; Use Campaign Map Editor > Strat > Factions > Diplomacy tab to define
; faction_standings (attitude values -1.00 to 1.00) and faction_relationships (at_war_with / allied_to).
`;

const MENU_XML_TEMPLATE = (campaigns) => {
  const items = campaigns.map(c => `
      <element>
        <type>custom</type>
        <custom_type>${c.name}</custom_type>
        <on_custom_select_card>CUSTOM_${c.name.toUpperCase()}</on_custom_select_card>
      </element>`).join('');
  return `; Add these entries to your ui/campmap/data/scrolls/campaign_selection_menu.xml
; or merge into the existing provincial campaigns block:
<campaign_selection_menu>
  <campaigns>${items}
  </campaigns>
</campaign_selection_menu>
`;
};

export default function CampaignManager() {
  const [campaigns, setCampaigns] = useState(loadCampaigns);
  const [showForm, setShowForm] = useState(false);
  const [editingId, setEditingId] = useState(null);
  const [duplicating, setDuplicating] = useState(null);
  const [exporting, setExporting] = useState(false);
  const [exported, setExported] = useState(false);
  const fileInputRef = useRef();
  const [importedFiles, setImportedFiles] = useState({}); // name -> file content

  const handleCreate = (data) => {
    const id = `camp_${Date.now()}`;
    const newCamp = { id, ...data, createdAt: new Date().toISOString() };
    const updated = [...campaigns, newCamp];
    setCampaigns(updated);
    saveCampaigns(updated);
    setShowForm(false);
    setDuplicating(null);
    setEditingId(null);
  };

  const handleDelete = (id) => {
    const updated = campaigns.filter(c => c.id !== id);
    setCampaigns(updated);
    saveCampaigns(updated);
  };

  const handleDuplicate = (camp) => {
    setDuplicating(camp);
    setShowForm(true);
  };

  const handleEdit = (camp) => {
    setEditingId(camp.id);
    setShowForm(true);
  };

  const handleUpdate = (data) => {
    const updated = campaigns.map(c => c.id === editingId ? { ...c, ...data } : c);
    setCampaigns(updated);
    saveCampaigns(updated);
    setShowForm(false);
    setEditingId(null);
  };

  const handleImportFolder = (e) => {
    const files = Array.from(e.target.files || []);
    const map = {};
    files.forEach(f => { map[f.name.toLowerCase()] = f; });
    setImportedFiles(map);
    e.target.value = '';
  };

  const handleExportZip = async () => {
    if (campaigns.length === 0) return;
    setExporting(true);
    setExported(false);
    const zip = new JSZip();

    // For each campaign, generate folder structure
    for (const c of campaigns) {
      const folder = `data/world/maps/campaign/custom/${c.name}/`;
      // descr_strat.txt
      const stratContent = c.customStratContent || DEFAULT_DESCR_STRAT(c.name);
      zip.file(folder + 'descr_strat.txt', stratContent);
      // Placeholder map files note
      zip.file(folder + '_README.txt',
        `Campaign: ${c.title} (${c.name})\n\nCopy your map TGA files here:\n  map_regions.tga\n  map_ground_types.tga\n  map_heights.tga\n  map_climates.tga\n  map_features.tga\n  map_fog.tga\n  map_geography.tga\n\nAlso place:\n  descr_regions.txt\n  descr_sm_factions.txt\n  descr_win_conditions.txt\n  map.rwm (generated by the game on first run)\n`
      );
    }

    // campaign_descriptions.txt (text/campaign_descriptions.txt)
    let campaignDesc = '¬\n';
    for (const c of campaigns) {
      campaignDesc += DEFAULT_CAMPAIGN_DESCRIPTIONS(c.name, c.title);
    }
    zip.file('data/text/campaign_descriptions.txt', campaignDesc);

    // menu XML hint
    zip.file('_MENU_XML_INSTRUCTIONS.txt', MENU_XML_TEMPLATE(campaigns));

    // Simple mod preset note for launchers/import tooling.
    const modName = (() => { try { return localStorage.getItem('m2tw_mod_name') || 'my_mod'; } catch { return 'my_mod'; } })();
    const openTWEMPPreset = `[ModPreset]
Name=${modName}
Campaigns=${campaigns.map(c => c.name).join(',')}
CampaignTitles=${campaigns.map(c => c.title).join(',')}
Version=1.0
Description=Custom campaigns created with Rome: Total War Mod Editor
`;
    zip.file('_rome_mod_preset.cfg', openTWEMPPreset);

    const blob = await zip.generateAsync({ type: 'blob' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `campaigns_${modName}.zip`;
    a.click();
    URL.revokeObjectURL(url);
    setExporting(false);
    setExported(true);
  };

  const editingCamp = editingId ? campaigns.find(c => c.id === editingId) : null;

  return (
    <div className="h-screen flex flex-col">
      {/* Toolbar */}
      <div className="h-10 border-b border-border flex items-center px-4 gap-3 shrink-0 bg-card/50">
        <Map className="w-4 h-4 text-primary shrink-0" />
        <span className="text-xs font-semibold text-foreground">Campaign Manager</span>
        <span className="text-[10px] text-muted-foreground">— Multiple Campaigns / Provincial Campaigns</span>
        <div className="ml-auto flex items-center gap-2">
          <label className="cursor-pointer">
            <input ref={fileInputRef} type="file" className="hidden" webkitdirectory="" directory="" multiple onChange={handleImportFolder} />
            <Button variant="outline" size="sm" className="h-7 text-[11px] gap-1.5 pointer-events-none" asChild>
              <span><FolderOpen className="w-3 h-3" /> Import base campaign folder</span>
            </Button>
          </label>
          {Object.keys(importedFiles).length > 0 && (
            <span className="text-[10px] text-green-400">{Object.keys(importedFiles).length} files staged</span>
          )}
          <Button size="sm" className="h-7 text-[11px] gap-1.5" onClick={() => { setShowForm(true); setDuplicating(null); setEditingId(null); }}>
            <Plus className="w-3.5 h-3.5" /> New Campaign
          </Button>
        </div>
      </div>

      <div className="flex flex-1 min-h-0">
        {/* Left: campaign list */}
        <ScrollArea className="flex-1">
          <div className="p-5 max-w-2xl space-y-4">
            {/* Tutorial info */}
            <div className="bg-primary/10 border border-primary/20 rounded-lg p-3 flex gap-3">
              <Info className="w-4 h-4 text-primary shrink-0 mt-0.5" />
              <div className="text-[11px] text-muted-foreground space-y-1">
                <p className="font-semibold text-foreground">How multiple campaigns work in Rome: Total War</p>
                <p>Place each campaign folder in <code className="font-mono bg-accent px-1 rounded">data/world/maps/campaign/custom/[campaign_name]/</code></p>
                <p>Each folder needs its own <code className="font-mono bg-accent px-1 rounded">descr_strat.txt</code> with <code className="font-mono bg-accent px-1 rounded">campaign [name]</code>, map TGA files, and entries in <code className="font-mono bg-accent px-1 rounded">data/text/campaign_descriptions.txt</code>.</p>
                <p>The menu XML in <code className="font-mono bg-accent px-1 rounded">ui/campmap/data/scrolls/</code> must list each campaign to appear in the singleplayer menu.</p>
              </div>
            </div>

            {/* Campaign cards */}
            {campaigns.length === 0 ? (
              <div className="text-center py-12 text-muted-foreground">
                <Map className="w-10 h-10 mx-auto mb-3 opacity-20" />
                <p className="text-sm">No campaigns yet.</p>
                <p className="text-xs mt-1">Click <strong>New Campaign</strong> to create one from scratch, or duplicate the imperial campaign.</p>
              </div>
            ) : (
              campaigns.map(c => (
                <CampaignCard
                  key={c.id}
                  campaign={c}
                  onEdit={() => handleEdit(c)}
                  onDelete={() => handleDelete(c.id)}
                  onDuplicate={() => handleDuplicate(c)}
                />
              ))
            )}

            {/* Export */}
            {campaigns.length > 0 && (
              <div className="space-y-2 pt-2">
                <Button
                  className="w-full h-11 gap-2"
                  onClick={handleExportZip}
                  disabled={exporting}
                >
                  {exporting ? (
                    <><div className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin" />Building…</>
                  ) : (
                    <><Download className="w-4 h-4" />Export Campaign Files (.zip)</>
                  )}
                </Button>
                {exported && (
                  <div className="flex items-center gap-2 text-green-400 text-xs justify-center">
                    <CheckCircle2 className="w-3.5 h-3.5" />
                    Downloaded! Extract into your mod folder root.
                  </div>
                )}
                <p className="text-[10px] text-muted-foreground text-center">
                  Generates <code className="font-mono bg-accent px-1 rounded">descr_strat.txt</code>, text entries, menu XML hints, and a small Rome launcher/import preset.
                </p>
              </div>
            )}
          </div>
        </ScrollArea>

        {/* Right: form panel */}
        {showForm && (
          <div className="w-96 border-l border-border shrink-0 flex flex-col">
            <div className="p-3 border-b border-border flex items-center gap-2">
              <span className="text-xs font-semibold text-foreground">
                {editingId ? 'Edit Campaign' : duplicating ? `Duplicate: ${duplicating.name}` : 'New Campaign'}
              </span>
              <button onClick={() => { setShowForm(false); setDuplicating(null); setEditingId(null); }}
                className="ml-auto text-muted-foreground hover:text-foreground text-xs">✕</button>
            </div>
            <ScrollArea className="flex-1">
              <CampaignForm
                initial={duplicating ? { ...duplicating, name: duplicating.name + '_copy', title: duplicating.title + ' Copy' } : editingCamp}
                onSubmit={editingId ? handleUpdate : handleCreate}
                onCancel={() => { setShowForm(false); setDuplicating(null); setEditingId(null); }}
                isDuplicate={!!duplicating}
              />
            </ScrollArea>
          </div>
        )}
      </div>
    </div>
  );
}
