import { parseTextLocFile, serializeTextLocFile } from '@/lib/textLocParser';

/**
 * Parser and serializer for export_descr_character_traits.txt and export_VnVs.txt
 */

// ── Text file parser (export_VnVs.txt / export_ancillaries.txt) ──────────────
// Format: { key } value  (wide-char spaced, BOM first line)
export function parseTextFile(raw) {
  return parseTextLocFile(raw);
}

export function serializeTextFile(map) {
  return serializeTextLocFile(map, { header: 'Generated by Mylae RTW/M2TW Mod Editor' });
}

// ── Traits file parser ────────────────────────────────────────────────────────

export function parseTraitsFile(raw) {
  const traits = [];
  const triggers = [];

  const lines = raw.split(/\r?\n/);
  let i = 0;

  while (i < lines.length) {
    const line = lines[i].replace(/;.*$/, '').trim();

    if (line.startsWith('Trait ')) {
      const { trait, end } = parseTrait(lines, i);
      traits.push(trait);
      i = end;
    } else if (line.startsWith('Trigger ')) {
      const { trigger, end } = parseTrigger(lines, i);
      triggers.push(trigger);
      i = end;
    } else {
      i++;
    }
  }

  return { traits, triggers };
}

function parseTrait(lines, start) {
  const nameLine = lines[start].replace(/;.*$/, '').trim();
  const traitName = nameLine.replace(/^Trait\s+/, '').trim();

  const trait = {
    name: traitName,
    characters: [],
    hidden: false,
    excludeCultures: [],
    noGoingBackLevel: null,
    antiTraits: [],
    levels: [],
    _comments: [],
  };

  let i = start + 1;

  while (i < lines.length) {
    const raw = lines[i];
    const line = raw.replace(/;.*$/, '').trim();

    // Next trait or trigger → stop
    if (line.startsWith('Trait ') || line.startsWith('Trigger ')) break;
    // Empty separator between traits
    if (!line) { i++; continue; }

    if (line.startsWith('Characters ')) {
      trait.characters = line.replace('Characters ', '').split(',').map(s => s.trim()).filter(Boolean);
    } else if (line === 'Hidden') {
      trait.hidden = true;
    } else if (line.startsWith('ExcludeCultures ')) {
      trait.excludeCultures = line.replace('ExcludeCultures ', '').split(',').map(s => s.trim()).filter(Boolean);
    } else if (line.startsWith('NoGoingBackLevel ')) {
      trait.noGoingBackLevel = parseInt(line.replace('NoGoingBackLevel ', '').trim(), 10);
    } else if (line.startsWith('AntiTraits ')) {
      trait.antiTraits = line.replace('AntiTraits ', '').split(',').map(s => s.trim()).filter(Boolean);
    } else if (line.startsWith('Level ')) {
      const { level, end } = parseTraitLevel(lines, i);
      trait.levels.push(level);
      i = end;
      continue;
    }

    i++;
  }

  return { trait, end: i };
}

function parseTraitLevel(lines, start) {
  const nameLine = lines[start].replace(/;.*$/, '').trim();
  const levelName = nameLine.replace(/^Level\s+/, '').trim();

  const level = {
    name: levelName,
    description: '',
    effectsDescription: '',
    gainMessage: '',
    loseMessage: '',
    epithet: '',
    threshold: 0,
    effects: [],
  };

  let i = start + 1;

  while (i < lines.length) {
    const raw = lines[i];
    const line = raw.replace(/;.*$/, '').trim();

    // Next level, trait, or trigger → stop
    if (line.startsWith('Level ') || line.startsWith('Trait ') || line.startsWith('Trigger ')) break;
    if (!line) { i++; continue; }

    if (line.startsWith('Description ')) {
      level.description = line.replace('Description ', '').trim();
    } else if (line.startsWith('EffectsDescription ')) {
      level.effectsDescription = line.replace('EffectsDescription ', '').trim();
    } else if (line.startsWith('GainMessage ')) {
      level.gainMessage = line.replace('GainMessage ', '').trim();
    } else if (line.startsWith('LoseMessage ')) {
      level.loseMessage = line.replace('LoseMessage ', '').trim();
    } else if (line.startsWith('Epithet ')) {
      level.epithet = line.replace('Epithet ', '').trim();
    } else if (line.startsWith('Threshold ')) {
      level.threshold = parseInt(line.replace('Threshold', '').trim(), 10);
    } else if (line.startsWith('Effect ')) {
      const parts = line.replace('Effect ', '').trim().split(/\s+/);
      if (parts.length >= 2) {
        level.effects.push({ attribute: parts[0], value: parseInt(parts[1], 10) });
      }
    }

    i++;
  }

  return { level, end: i };
}

function parseTrigger(lines, start) {
  const nameLine = lines[start].replace(/;.*$/, '').trim();
  const triggerName = nameLine.replace(/^Trigger\s+/, '').trim();

  const trigger = {
    name: triggerName,
    whenToTest: '',
    conditions: [],
    affects: [],
    rawLines: [],
  };

  let i = start + 1;
  let rawBlock = [lines[start]];

  while (i < lines.length) {
    const raw = lines[i];
    rawBlock.push(raw);
    const line = raw.replace(/;.*$/, '').trim();

    if (line.startsWith('Trait ') || line.startsWith('Trigger ') || line.startsWith('Ancillary ')) break;
    if (!line) { i++; continue; }

    if (line.startsWith('WhenToTest ')) {
      trigger.whenToTest = line.replace('WhenToTest ', '').trim();
    } else if (line.startsWith('Condition ') || line.startsWith('and ') || line.startsWith('or ')) {
      trigger.conditions.push(line);
    } else if (line.startsWith('Affects ')) {
      const parts = line.replace('Affects ', '').trim().split(/\s+/);
      trigger.affects.push({
        trait: parts[0],
        value: parseInt(parts[1] || '0', 10),
        chance: parseInt(parts[3] || '100', 10),
      });
    }

    i++;
  }

  trigger.rawLines = rawBlock;
  return { trigger, end: i };
}

// ── Traits serializer ─────────────────────────────────────────────────────────

export function serializeTraitsFile(data) {
  const { traits, triggers } = data;
  const lines = [
    ';This file is generated by the Rome / Medieval II Mod Editor',
    ';Please modify the spreadsheet and re-export the data, rather than editing this file directly',
    '',
    ';===============================================================',
    ';== TRAIT DATA STARTS HERE ==',
    ';===============================================================',
    '',
  ];

  for (const trait of traits) {
    lines.push(';------------------------------------------');
    lines.push(`Trait ${trait.name}`);
    if (trait.characters.length > 0) {
      lines.push(`    Characters ${trait.characters.join(', ')}`);
    }
    if (trait.hidden) lines.push('    Hidden');
    if (trait.excludeCultures.length > 0) {
      lines.push(`    ExcludeCultures ${trait.excludeCultures.join(', ')}`);
    }
    if (trait.noGoingBackLevel !== null) {
      lines.push(`    NoGoingBackLevel  ${trait.noGoingBackLevel} `);
    }
    if (trait.antiTraits.length > 0) {
      lines.push(`    AntiTraits ${trait.antiTraits.join(', ')}`);
    }
    lines.push('');

    for (const level of trait.levels) {
      lines.push(`    Level ${level.name}`);
      if (level.description) lines.push(`        Description ${level.description}`);
      if (level.effectsDescription) lines.push(`        EffectsDescription ${level.effectsDescription}`);
      if (level.gainMessage) lines.push(`        GainMessage ${level.gainMessage}`);
      if (level.loseMessage) lines.push(`        LoseMessage ${level.loseMessage}`);
      if (level.epithet) lines.push(`        Epithet ${level.epithet}`);
      lines.push(`        Threshold  ${level.threshold} `);
      lines.push('');
      for (const effect of level.effects) {
        lines.push(`        Effect ${effect.attribute}  ${effect.value} `);
      }
      lines.push('');
    }

    lines.push('');
  }

  if (triggers.length > 0) {
    lines.push(';===============================================================');
    lines.push(';== TRAIT TRIGGERS START HERE ==');
    lines.push(';===============================================================');
    lines.push('');

    for (const trigger of triggers) {
      lines.push(`Trigger ${trigger.name}`);
      if (trigger.whenToTest) lines.push(`    WhenToTest ${trigger.whenToTest}`);
      lines.push('');
      for (const cond of (trigger.conditions || [])) {
        lines.push(`    ${cond}`);
      }
      if (trigger.conditions && trigger.conditions.length > 0) lines.push('');
      for (const aff of (trigger.affects || [])) {
        lines.push(`    Affects ${aff.trait}  ${aff.value}  chance  ${aff.chance} `);
      }
      lines.push('');
    }
  }

  return lines.join('\n');
}
