import React, { useState, useEffect, useRef } from 'react';
import { Download, Package, CheckCircle, AlertCircle, CloudUpload, Link, LogOut } from 'lucide-react';
import { LAYER_DEFS } from '@/lib/mapLayerStore';
import { downloadTGA, validateRegionMap } from '@/lib/tgaEncoder';
import JSZip from 'jszip';
import { base44 } from '@/api/base44Client';

const CONNECTOR_ID = '6a44eaca88b0c5609fcdc001';

export default function ExportPanel({ layers, mapWidth, mapHeight, extraAssets = [], settlements = [], historicTagStates = {} }) {
  const [results, setResults] = useState([]);
  const [exporting, setExporting] = useState(false);
  const [driveConnected, setDriveConnected] = useState(false);
  const [driveUploading, setDriveUploading] = useState(false);
  const [driveResult, setDriveResult] = useState(null); // { fileName, webViewLink } or { error }
  const popupRef = useRef(null);

  // Rule 2: check connection by attempting a benign fetch; Drive has no status endpoint so we try connectAppUser and catch
  useEffect(() => {
    base44.auth.isAuthenticated().then(async (authed) => {
      if (!authed) return;
      // Try to get a connect URL — if the user is already connected, we detect it on upload attempt
      // Instead, just mark as "ready to connect" — we'll detect on upload
      setDriveConnected(false); // will be confirmed on first successful upload
    });
  }, []);

  const handleDriveConnect = async () => {
    const url = await base44.connectors.connectAppUser(CONNECTOR_ID);
    const popup = window.open(url, '_blank', 'width=600,height=700');
    popupRef.current = popup;
    const timer = setInterval(() => {
      if (!popup || popup.closed) {
        clearInterval(timer);
        setDriveConnected(true);
      }
    }, 500);
  };

  const handleDriveDisconnect = async () => {
    await base44.connectors.disconnectAppUser(CONNECTOR_ID);
    setDriveConnected(false);
    setDriveResult(null);
  };

  const buildZipBase64 = async () => {
    const zip = new JSZip();
    for (const def of LAYER_DEFS) {
      const layer = layers[def.id];
      if (!layer?.imageData) continue;
      const { encodeTGA } = await import('@/lib/tgaEncoder');
      const buf = encodeTGA(layer.imageData, def.mode);
      zip.file(def.filename, buf);
    }
    if (settlements.length > 0) {
      const lines = [
        `; map_regions.txt — generated by M2TW New Map Editor`, `; province_name  r g b  city_x city_y  port_x port_y`, ``,
        ...settlements.map(s => `${s.name}  ${s.rgb[0]} ${s.rgb[1]} ${s.rgb[2]}  ${s.px} ${s.py}  0 0`),
      ].join('\n');
      zip.file('reference/map_regions.txt', lines);
    }
    const doneTags = Object.entries(historicTagStates).filter(([, s]) => s?.status === 'done');
    if (doneTags.length > 0) {
      const lines = [
        `; OSM Historic Features`, ``,
        ...doneTags.flatMap(([k, s]) => [`; === ${s.label} ===`, ...(s.points || []).map(p => `${s.label}; x${p.px}; y${p.py}`), ``]),
      ].join('\n');
      zip.file('reference/historic_features.txt', lines);
    }
    for (const asset of extraAssets) {
      const data = asset.getData();
      if (asset.type === 'png') {
        const res = await fetch(data); const buf = await res.arrayBuffer();
        zip.file(`reference/${asset.filename}`, buf);
      } else { zip.file(`reference/${asset.filename}`, data); }
    }
    const blob = await zip.generateAsync({ type: 'blob' });
    return new Promise((resolve) => {
      const reader = new FileReader();
      reader.onloadend = () => resolve(reader.result.split(',')[1]);
      reader.readAsDataURL(blob);
    });
  };

  const uploadToDrive = async () => {
    setDriveUploading(true);
    setDriveResult(null);
    try {
      const fileBase64 = await buildZipBase64();
      const fileName = `m2tw_map_layers_${new Date().toISOString().slice(0, 10)}.zip`;
      const res = await base44.functions.invoke('uploadToDrive', { fileName, fileBase64 });
      if (res.data?.error) { setDriveResult({ error: res.data.error }); }
      else { setDriveConnected(true); setDriveResult({ fileName: res.data.fileName, webViewLink: res.data.webViewLink }); }
    } catch (e) {
      setDriveResult({ error: e.message });
    }
    setDriveUploading(false);
  };

  const validateAll = () => {
    const res = [];
    for (const def of LAYER_DEFS) {
      const layer = layers[def.id];
      if (!layer?.imageData) { res.push({ id: def.id, label: def.label, status: 'missing' }); continue; }
      if (def.id === 'regions') {
        const v = validateRegionMap(layer.imageData);
        res.push({ id: def.id, label: def.label, status: v.valid ? 'ok' : 'warn', detail: `${v.regionCount} regions` });
      } else {
        res.push({ id: def.id, label: def.label, status: 'ok' });
      }
    }
    setResults(res);
    return res;
  };

  const exportSingle = (defId) => {
    const def = LAYER_DEFS.find(d => d.id === defId);
    const layer = layers[defId];
    if (!def || !layer?.imageData) return;
    downloadTGA(layer.imageData, def.filename, def.mode);
  };

  const exportAll = async () => {
    setExporting(true);
    validateAll();
    const b64 = await buildZipBase64();
    const binaryStr = atob(b64);
    const bytes = new Uint8Array(binaryStr.length);
    for (let i = 0; i < binaryStr.length; i++) bytes[i] = binaryStr.charCodeAt(i);
    const blob = new Blob([bytes], { type: 'application/zip' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a'); a.href = url; a.download = 'm2tw_map_layers.zip'; a.click();
    URL.revokeObjectURL(url);
    setExporting(false);
  };

  return (
    <div className="space-y-3">
      <div className="flex gap-2">
        <button onClick={validateAll}
          className="flex-1 flex items-center justify-center gap-1.5 px-3 py-2 rounded text-[11px] bg-slate-700 border border-slate-600 text-slate-200 hover:bg-slate-600 transition-colors">
          <CheckCircle className="w-3.5 h-3.5" /> Validate Layers
        </button>
        <button onClick={exportAll} disabled={exporting}
          className="flex-1 flex items-center justify-center gap-1.5 px-3 py-2 rounded text-[11px] bg-amber-600 border border-amber-500 text-white hover:bg-amber-500 disabled:opacity-50 transition-colors">
          <Package className="w-3.5 h-3.5" /> {exporting ? 'Exporting…' : 'Export Bundle'}
        </button>
      </div>

      {results.length > 0 && (
        <div className="space-y-1">
          {results.map(r => (
            <div key={r.id} className="flex items-center gap-2 px-2 py-1 rounded bg-slate-800 border border-slate-700">
              {r.status === 'ok' && <CheckCircle className="w-3 h-3 text-green-500 shrink-0" />}
              {r.status === 'warn' && <AlertCircle className="w-3 h-3 text-amber-400 shrink-0" />}
              {r.status === 'missing' && <AlertCircle className="w-3 h-3 text-red-400 shrink-0" />}
              <span className="text-[11px] text-slate-300 flex-1">{r.label}</span>
              {r.detail && <span className="text-[9px] text-slate-500">{r.detail}</span>}
              {r.status !== 'missing' && (
                <button onClick={() => exportSingle(r.id)}
                  className="text-slate-500 hover:text-amber-400 transition-colors">
                  <Download className="w-3 h-3" />
                </button>
              )}
            </div>
          ))}
        </div>
      )}

      {extraAssets.length > 0 && (
        <div className="space-y-1">
          <p className="text-[10px] text-slate-500 font-semibold">Reference Assets (included in bundle)</p>
          {extraAssets.map(asset => (
            <div key={asset.filename} className="flex items-center gap-2">
              <span className={`text-[9px] font-mono px-1 rounded shrink-0 ${asset.type === 'png' ? 'bg-blue-900/40 text-blue-400' : 'bg-amber-900/40 text-amber-400'}`}>{asset.type}</span>
              <span className="text-[10px] text-slate-400 flex-1 font-mono truncate">{asset.filename}</span>
              <button
                onClick={() => {
                  const data = asset.getData();
                  if (asset.type === 'png') {
                    const a = document.createElement('a'); a.href = data; a.download = asset.filename; a.click();
                  } else {
                    const blob = new Blob([data], { type: 'text/plain' });
                    const a = document.createElement('a'); a.href = URL.createObjectURL(blob); a.download = asset.filename; a.click();
                  }
                }}
                className="text-slate-500 hover:text-amber-400 transition-colors shrink-0">
                <Download className="w-3 h-3" />
              </button>
            </div>
          ))}
        </div>
      )}

      {/* Google Drive Upload */}
      <div className="border border-slate-700 rounded p-2.5 space-y-2">
        <p className="text-[10px] text-slate-300 font-semibold flex items-center gap-1.5"><CloudUpload className="w-3.5 h-3.5 text-blue-400" /> Upload to Google Drive</p>
        {!driveConnected ? (
          <button onClick={handleDriveConnect}
            className="w-full flex items-center justify-center gap-2 px-3 py-1.5 rounded text-[10px] bg-blue-700 border border-blue-600 text-white hover:bg-blue-600 transition-colors font-semibold">
            <CloudUpload className="w-3 h-3" /> Connect Google Drive
          </button>
        ) : (
          <div className="space-y-1.5">
            <div className="flex items-center gap-2">
              <CheckCircle className="w-3 h-3 text-green-400 shrink-0" />
              <span className="text-[10px] text-green-400 flex-1">Drive connected</span>
              <button onClick={handleDriveDisconnect} className="text-slate-500 hover:text-red-400 transition-colors" title="Disconnect">
                <LogOut className="w-3 h-3" />
              </button>
            </div>
            <button onClick={uploadToDrive} disabled={driveUploading}
              className="w-full flex items-center justify-center gap-2 px-3 py-1.5 rounded text-[10px] bg-blue-700 border border-blue-600 text-white hover:bg-blue-600 disabled:opacity-50 transition-colors font-semibold">
              <CloudUpload className="w-3 h-3" /> {driveUploading ? 'Uploading…' : 'Upload Bundle to Drive'}
            </button>
          </div>
        )}
        {driveResult?.error && <p className="text-[9px] text-red-400 bg-red-900/20 border border-red-600/30 rounded px-2 py-1">{driveResult.error}</p>}
        {driveResult?.webViewLink && (
          <a href={driveResult.webViewLink} target="_blank" rel="noreferrer"
            className="flex items-center gap-1.5 text-[9px] text-blue-400 hover:text-blue-300 truncate">
            <Link className="w-3 h-3 shrink-0" /> {driveResult.fileName}
          </a>
        )}
      </div>

      <div className="space-y-1">
        <p className="text-[10px] text-slate-500 font-semibold">Export Individual</p>
        {LAYER_DEFS.map(def => (
          <div key={def.id} className="flex items-center gap-2">
            <div className="w-2 h-2 rounded-sm shrink-0" style={{ backgroundColor: def.defaultColor }} />
            <span className="text-[11px] text-slate-400 flex-1 font-mono">{def.filename}</span>
            <button onClick={() => exportSingle(def.id)}
              disabled={!layers[def.id]?.imageData}
              className="text-slate-500 hover:text-amber-400 disabled:opacity-30 transition-colors">
              <Download className="w-3 h-3" />
            </button>
          </div>
        ))}
      </div>
    </div>
  );
}