import { parseTextLocFile, serializeTextLocFile } from '@/lib/textLocParser';

/**
 * Parser and serializer for export_descr_ancillaries.txt and export_ancillaries.txt
 */

// ── Text file parser (same format as VnVs) ───────────────────────────────────
export function parseTextFile(raw) {
  return parseTextLocFile(raw);
}

export function serializeTextFile(map) {
  return serializeTextLocFile(map, { header: 'Generated by Mylae RTW/M2TW Mod Editor' });
}

// ── Ancillaries file parser ───────────────────────────────────────────────────

export function parseAncillariesFile(raw) {
  const ancillaries = [];
  const triggers = [];

  const lines = raw.split(/\r?\n/);
  let i = 0;
  let inTriggerSection = false;

  while (i < lines.length) {
    const line = lines[i].replace(/;.*$/, '').trim();

    if (line.startsWith('Ancillary ')) {
      const { ancillary, end } = parseAncillary(lines, i);
      ancillaries.push(ancillary);
      i = end;
    } else if (line.startsWith('Trigger ')) {
      inTriggerSection = true;
      const { trigger, end } = parseTrigger(lines, i);
      triggers.push(trigger);
      i = end;
    } else {
      i++;
    }
  }

  return { ancillaries, triggers };
}

function parseAncillary(lines, start) {
  const nameLine = lines[start].replace(/;.*$/, '').trim();
  const name = nameLine.replace(/^Ancillary\s+/, '').trim();

  const anc = {
    name,
    type: '',
    transferable: 1,
    image: '',
    unique: false,
    excludedAncillaries: [],
    excludeCultures: [],
    description: '',
    effectsDescription: '',
    effects: [],
  };

  let i = start + 1;

  while (i < lines.length) {
    const line = lines[i].replace(/;.*$/, '').trim();

    if (line.startsWith('Ancillary ') || line.startsWith('Trigger ')) break;
    if (!line) { i++; continue; }

    if (line.startsWith('Type ')) {
      anc.type = line.replace('Type ', '').trim();
    } else if (line.startsWith('Transferable ')) {
      anc.transferable = parseInt(line.replace('Transferable', '').trim(), 10);
    } else if (line.startsWith('Image ')) {
      anc.image = line.replace('Image ', '').trim();
    } else if (line === 'Unique') {
      anc.unique = true;
    } else if (line.startsWith('ExcludedAncillaries ')) {
      anc.excludedAncillaries = line.replace('ExcludedAncillaries ', '').split(',').map(s => s.trim()).filter(Boolean);
    } else if (line.startsWith('ExcludeCultures ')) {
      anc.excludeCultures = line.replace('ExcludeCultures ', '').split(',').map(s => s.trim()).filter(Boolean);
    } else if (line.startsWith('Description ')) {
      anc.description = line.replace('Description ', '').trim();
    } else if (line.startsWith('EffectsDescription ')) {
      anc.effectsDescription = line.replace('EffectsDescription ', '').trim();
    } else if (line.startsWith('Effect ')) {
      const parts = line.replace('Effect ', '').trim().split(/\s+/);
      if (parts.length >= 2) {
        anc.effects.push({ attribute: parts[0], value: parseInt(parts[1], 10) });
      }
    }

    i++;
  }

  return { ancillary: anc, end: i };
}

function parseTrigger(lines, start) {
  const nameLine = lines[start].replace(/;.*$/, '').trim();
  const name = nameLine.replace(/^Trigger\s+/, '').trim();

  const trigger = {
    name,
    whenToTest: '',
    conditions: [],
    acquireAncillary: null,
    rawLines: [],
  };

  let i = start + 1;
  const rawBlock = [lines[start]];

  while (i < lines.length) {
    const raw = lines[i];
    rawBlock.push(raw);
    const line = raw.replace(/;.*$/, '').trim();

    if (line.startsWith('Ancillary ') || line.startsWith('Trigger ')) break;
    if (!line) { i++; continue; }

    if (line.startsWith('WhenToTest ')) {
      trigger.whenToTest = line.replace('WhenToTest ', '').trim();
    } else if (line.startsWith('Condition ') || line.startsWith('and ') || line.startsWith('or ')) {
      trigger.conditions.push(line);
    } else if (line.startsWith('AcquireAncillary ')) {
      const parts = line.replace('AcquireAncillary ', '').trim().split(/\s+/);
      trigger.acquireAncillary = {
        name: parts[0],
        chance: parseInt(parts[2] || '100', 10),
      };
    }

    i++;
  }

  trigger.rawLines = rawBlock;
  return { trigger, end: i };
}

// ── Ancillaries serializer ────────────────────────────────────────────────────

export function serializeAncillariesFile(data) {
  const { ancillaries, triggers } = data;
  const lines = [
    ';This file is generated by the Rome / Medieval II Mod Editor',
    ';Please modify the spreadsheet and re-export the data, rather than editing this file directly',
    '',
    ';===============================================================',
    ';== ANCILLARY DATA STARTS HERE ==',
    ';===============================================================',
    '',
  ];

  for (const anc of ancillaries) {
    lines.push(';------------------------------------------');
    lines.push(`Ancillary ${anc.name}`);
    lines.push(`    Type ${anc.type}`);
    lines.push(`    Transferable  ${anc.transferable} `);
    if (anc.image) lines.push(`    Image ${anc.image}`);
    if (anc.unique) lines.push('    Unique');
    if (anc.excludedAncillaries.length > 0) {
      lines.push(`    ExcludedAncillaries ${anc.excludedAncillaries.join(', ')}`);
    }
    if (anc.excludeCultures.length > 0) {
      lines.push(`    ExcludeCultures ${anc.excludeCultures.join(', ')}`);
    }
    if (anc.description) lines.push(`    Description ${anc.description}`);
    if (anc.effectsDescription) lines.push(`    EffectsDescription ${anc.effectsDescription}`);
    for (const effect of anc.effects) {
      lines.push(`    Effect ${effect.attribute}  ${effect.value} `);
    }
    lines.push('');
  }

  if (triggers.length > 0) {
    lines.push(';===============================================================');
    lines.push(';== ANCILLARY TRIGGERS START HERE ==============================');
    lines.push(';===============================================================');
    lines.push('');

    for (const trigger of triggers) {
      lines.push(`Trigger ${trigger.name}`);
      if (trigger.whenToTest) lines.push(`    WhenToTest ${trigger.whenToTest}`);
      lines.push('');
      for (const cond of (trigger.conditions || [])) {
        lines.push(`    ${cond}`);
      }
      if (trigger.conditions && trigger.conditions.length > 0) lines.push('');
      if (trigger.acquireAncillary) {
        lines.push(`    AcquireAncillary ${trigger.acquireAncillary.name}  chance  ${trigger.acquireAncillary.chance} `);
      }
      lines.push('');
    }
  }

  return lines.join('\n');
}
