/**
 * Layer definitions for the M2TW Campaign Map Viewer.
 * Each layer knows its file name, display label, blend mode, default opacity,
 * and colour legend for the pixel-probe tooltip.
 */

export const LAYER_DEFS = [
  {
    id: 'heights',
    label: 'Heights',
    filename: 'map_heights.tga',
    defaultOpacity: 1.0,
    defaultVisible: true,
    blendMode: 'source-over',
    description: 'Grayscale elevation. Blue (0,0,253) = sea; grey scale = land elevation.',
    legend: [
      { color: [0,0,253], label: 'Sea' },
      { color: [1,1,1],   label: 'Low land (dark)' },
      { color: [255,255,255], label: 'High land (bright)' },
    ],
  },
  {
    id: 'ground',
    label: 'Ground Types',
    filename: 'map_ground_types.tga',
    defaultOpacity: 1.0,
    defaultVisible: true,
    blendMode: 'source-over',
    description: 'Terrain type per tile (2× region size +1).',
    legend: [
      { color: [0,128,128],   label: 'Fertile Low' },
      { color: [96,160,64],   label: 'Fertile Medium' },
      { color: [101,124,0],   label: 'Fertile High' },
      { color: [0,0,0],       label: 'Wilderness' },
      { color: [196,128,128], label: 'Mountains High' },
      { color: [98,65,65],    label: 'Mountains Low' },
      { color: [128,128,64],  label: 'Hills' },
      { color: [0,64,0],      label: 'Forest Dense (impassable)' },
      { color: [0,128,0],     label: 'Forest Sparse' },
      { color: [0,255,128],   label: 'Swamp' },
      { color: [255,255,255], label: 'Beach' },
      { color: [64,64,64],    label: 'Impassable Land' },
      { color: [0,0,64],      label: 'Impassable Sea' },
      { color: [64,0,0],      label: 'Ocean' },
      { color: [128,0,0],     label: 'Sea Deep' },
      { color: [196,0,0],     label: 'Sea Shallow' },
    ],
  },
  {
    id: 'climates',
    label: 'Climates',
    filename: 'map_climates.tga',
    defaultOpacity: 0.6,
    defaultVisible: false,
    blendMode: 'source-over',
    description: 'Climate zones (same size as ground types).',
    legend: [
      { color: [236,0,140],   label: 'Mediterranean' },
      { color: [102,45,145],  label: 'Sandy Desert' },
      { color: [146,39,143],  label: 'Rocky Desert' },
      { color: [237,20,91],   label: 'Temperate Grassland Fertile' },
      { color: [237,28,36],   label: 'Steppe' },
      { color: [242,101,34],  label: 'Temperate Deciduous Forest' },
      { color: [247,148,29],  label: 'Temperate Coniferous Forest' },
      { color: [255,242,0],   label: 'Swamp' },
      { color: [141,198,63],  label: 'Highland' },
      { color: [57,181,74],   label: 'Alpine' },
      { color: [0,166,81],    label: 'Tropical' },
      { color: [0,114,188],   label: 'Semi-Arid' },
    ],
  },
  {
    id: 'regions',
    label: 'Regions',
    filename: 'map_regions.tga',
    exportOrigin: 'bottom-left',
    defaultOpacity: 0.5,
    defaultVisible: true,
    blendMode: 'source-over',
    description: 'Region colours (unique per region). Black pixel = city. White pixel = port.',
    legend: [
      { color: [0,0,0],       label: 'City location' },
      { color: [255,255,255], label: 'Port location' },
      { color: [41,140,233],  label: 'Sea' },
    ],
  },
  {
    id: 'features',
    label: 'Features',
    filename: 'map_features.tga',
    defaultOpacity: 1.0,
    defaultVisible: true,
    blendMode: 'source-over',
    description: 'Rivers, cliffs, land-bridges, volcanoes.',
    legend: [
      { color: [0,0,255],     label: 'River' },
      { color: [0,255,255],   label: 'Ford' },
      { color: [255,255,255], label: 'River origin' },
      { color: [255,255,0],   label: 'Cliff' },
      { color: [0,255,0],     label: 'Land-bridge' },
      { color: [255,0,0],     label: 'Volcano' },
    ],
  },
  {
    id: 'fog',
    label: 'Fog of War',
    filename: 'map_fog.tga',
    defaultOpacity: 0.4,
    defaultVisible: false,
    blendMode: 'source-over',
    description: 'Black = fogged (hidden). White = visible.',
    legend: [
      { color: [0,0,0],       label: 'Hidden (fog)' },
      { color: [255,255,255], label: 'Visible' },
    ],
  },
];

export const LAYER_BY_ID = Object.fromEntries(LAYER_DEFS.map(l => [l.id, l]));
